# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mcLrxmzG_jhPBA0-Wcb3PZI3JQDua0_Y
"""

# streamlit_app.py

import streamlit as st
import pandas as pd
import plotly.express as px

# Load the data
@st.cache_data
def load_data():
    file_path = "resources-and-energy-major-projects-2024-data.xlsx"
    df = pd.read_excel(file_path, sheet_name="Consolidated", skiprows=6)
    df = df.rename(columns={
        "Project": "Project",
        "State": "State",
        "Cost Estimate $Am": "Cost",
        "Construction Employment Estimate": "ConstructionJobs",
        "Operating Employment Estimate": "OperatingJobs",
        "Estimated Start Commercial Operation": "StartDate",
        "Latitude": "Lat",
        "Longitude": "Lon",
        "Critical mineral": "IsCritical"
    })
    df["StartDate"] = pd.to_datetime(df["StartDate"], errors="coerce")
    df["Cost"] = pd.to_numeric(df["Cost"], errors="coerce")
    df = df.dropna(subset=["Project", "State", "Cost", "Lat", "Lon"])
    return df

df = load_data()

# Title
st.title("🔋 AusEnergyPulse: Renewable Investment Dashboard")

# Filter
selected_state = st.selectbox("Select State:", options=["All"] + sorted(df["State"].unique()))
if selected_state != "All":
    df = df[df["State"] == selected_state]

# Map
st.subheader("📍 Project Locations")
st.map(df[["Lat", "Lon"]])

# Bar Chart by Resource Type
st.subheader("💰 Total Investment by Resource Type")
investment_by_resource = df.groupby("Resource")["Cost"].sum().sort_values(ascending=False)
st.bar_chart(investment_by_resource)

# Table
st.subheader("📝 Project Data")
st.dataframe(df[["Project", "State", "Cost", "StartDate", "IsCritical"]].sort_values("Cost", ascending=False))